controller_list:
  - name: /ar607/ar607_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory 
    joints: [joint1, joint2, joint3, joint4, joint5, joint6]

  - name: /ar607/hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory 
    joints: [finger_joint1, finger_joint2]
