topic_list:
    - name: right_arm_controller
      ns: left
      group: 0
      ip: 192.168.1.11
      port: 11000
      joints: [right_arm_joint1, right_arm_joint2, right_arm_joint3, right_arm_joint4, right_arm_joint5, right_arm_joint6, right_arm_joint7]
    - name: right_arm_controller
      ns: right
      group: 1
      ip: 192.168.1.159
      port: 11000
      joints: [right_arm_joint1, right_arm_joint2, right_arm_joint3, right_arm_joint4, right_arm_joint5, right_arm_joint6, right_arm_joint7]