# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: home_pos
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7
  gains:
    right_arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1