controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
initial:  # Define initial robot poses.
  - group: right_arm
    pose: HOME